### ISSUE TITLE
The SECRET_KEY setting must not be empty

### ISSUE THREAD

**Issue by ghost** [LexPredict/lexpredict-contraxsuite-deploy#19]
I am using ubuntu 16.04.
I have generated a key online for django from http://www.miniwebtool.com/django-secret-key-generator/ then input in the /opt/lexpredict-contraxsuite/contraxsuite_services/settings.py as ( SECRET_KEY = "yj6o@&vrar6^l1u68!bxugj@xr4&5)zzk!h1qw&13^&@2d3wp#") and also in /opt/lexpredict-contraxsuite-deploy/local/local_settings.py files.
after following all the steps of local machine installation setup mentioned in
https://github.com/LexPredict/lexpredict-contraxsuite/blob/master/documentation/Installation%20and%20Configuration/Quick%20Start%20Installation%20Guide%20for%20Linux.pdf
I am executing the following commad:
bash setup_local.sh | tee -a log.txt

after few steps of exection, I am getting the following error:
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty

need help to resolve this. I don't know where I am doing mistake.

**Comment by reddalexx** [comment]
Currently we use docker based approach for application deployment, see
https://github.com/LexPredict/lexpredict-contraxsuite/tree/master/docker

We had a lot of changes since we used lexpredict-contraxsuite-deploy for deployment last time.
I made some important updates there and it should work now.
So please update it using git pull and try again.

But I would recommend tot use docker.

**Comment by SandeepKumarJoshi** [comment]
Even after taking the update of  'lexpredict-contraxsuite-deploy' using git pull, I am facing the same issue. Below is the stach trace.

$ /opt/ve/bin/celery multi restart worker -A apps -B -Q serial --concurrency=1 -Ofair -l DEBUG -n beat@%h ->
[localhost] out: celery multi v4.2.0 (windowlicker)
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 365, in find_app
[localhost] out:     found = sym.app
[localhost] out: AttributeError: module 'apps' has no attribute 'app'
[localhost] out: 
[localhost] out: During handling of the above exception, another exception occurred:
[localhost] out: 
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 370, in find_app
[localhost] out:     found = sym.celery
[localhost] out: AttributeError: module 'apps' has no attribute 'celery'
[localhost] out: 
[localhost] out: During handling of the above exception, another exception occurred:
[localhost] out: 
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 359, in find_app
[localhost] out:     sym = symbol_by_name(app, imp=imp)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 504, in symbol_by_name
[localhost] out:     return imports.symbol_by_name(name, imp=imp)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
[localhost] out:     return getattr(module, cls_name) if cls_name else module
[localhost] out: AttributeError: module 'apps' has no attribute 'celery'
[localhost] out: 
[localhost] out: During handling of the above exception, another exception occurred:
[localhost] out: 
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
[localhost] out:     "__main__", mod_spec)
[localhost] out:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
[localhost] out:     exec(code, run_globals)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 20, in <module>
[localhost] out:     main()
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/__main__.py", line 16, in main
[localhost] out:     _main()
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 322, in main
[localhost] out:     cmd.execute_from_commandline(argv)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
[localhost] out:     super(CeleryCommand, self).execute_from_commandline(argv)))
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
[localhost] out:     argv = self.setup_app_from_commandline(argv)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
[localhost] out:     self.app = self.find_app(app)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/bin/base.py", line 501, in find_app
[localhost] out:     return find_app(app, symbol_by_name=self.symbol_by_name)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 378, in find_app
[localhost] out:     symbol_by_name=symbol_by_name, imp=imp,
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/app/utils.py", line 362, in find_app
[localhost] out:     sym = imp(app)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
[localhost] out:     return imp(module, package=package)
[localhost] out:   File "/opt/ve/lib/python3.5/importlib/__init__.py", line 126, in import_module
[localhost] out:     return _bootstrap._gcd_import(name[level:], package, level)
[localhost] out:   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[localhost] out:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[localhost] out:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[localhost] out:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[localhost] out:   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[localhost] out:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[localhost] out:   File "/opt/lexpredict-contraxsuite/contraxsuite_services/apps/celery.py", line 45, in <module>
[localhost] out:     django.setup()
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
[localhost] out:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
[localhost] out:     self._setup(name)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
[localhost] out:     self._wrapped = Settings(settings_module)
[localhost] out:   File "/opt/ve/lib/python3.5/site-packages/django/conf/__init__.py", line 129, in __init__
[localhost] out:     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
[localhost] out: django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[localhost] out: > Restarting node worker@beat@osboxes: * Child terminated with exit code 1
[localhost] out: FAILED
[localhost] out: 

Fatal error: run() received nonzero return code 1 while executing!

Requested: /opt/ve/bin/celery multi restart worker -A apps -B -Q serial --concurrency=1 -Ofair -l DEBUG -n beat@%h
Executed: /bin/bash -l -c "cd /opt/lexpredict-contraxsuite/contraxsuite_services >/dev/null && /opt/ve/bin/celery multi restart worker -A apps -B -Q serial --concurrency=1 -Ofair -l DEBUG -n beat@%h"

Aborting.
Disconnecting from localhost... done.

**Comment by reddalexx** [comment]
That means that probably local_setting.py template wasn't transfered  into destination folder.
go to deploy folder `cd lexpredict-contraxsuite-deploy`
activate virtual environment `source ve/bin/activate`
run `fab -c local/fabricrc upload_template_and_reload:settings` to apply local settings
run `fab -c local/fabricrc start` to start application
then open browser at `localhost`

**Comment by SandeepKumarJoshi** [comment]
@reddalexx: As per your suggestion, I have tried the docker setup and followed the steps mentioned here: https://github.com/LexPredict/lexpredict-contraxsuite/tree/master/docker
But it didn't load the Contraxsuite application at http://localhost:65080
I have used a Clean Ubuntu 16.04 machine having more than 8GB RAM. Below are the screenshots attached of the step by step execution.
![screenshot from 2018-07-19 02-25-09](https://user-images.githubusercontent.com/6755456/42926735-e823a052-8b4f-11e8-98ac-e5a9f59c4825.png)
![screenshot from 2018-07-19 02-26-58](https://user-images.githubusercontent.com/6755456/42926740-ec43a60a-8b4f-11e8-8450-ce734e767bae.png)
![screenshot from 2018-07-19 02-27-26](https://user-images.githubusercontent.com/6755456/42926747-ee21493c-8b4f-11e8-8fae-9ed586d7be5c.png)
![screenshot from 2018-07-19 02-28-00](https://user-images.githubusercontent.com/6755456/42926757-f6a5a184-8b4f-11e8-9fff-35a2b38fefdf.png)
![screenshot from 2018-07-19 02-29-09](https://user-images.githubusercontent.com/6755456/42926767-fd000592-8b4f-11e8-9e4d-e7f4021ae0af.png)
![screenshot from 2018-07-19 02-29-17](https://user-images.githubusercontent.com/6755456/42926769-0132458a-8b50-11e8-896f-1bdbb9d96adf.png)
![screenshot from 2018-07-19 02-29-25](https://user-images.githubusercontent.com/6755456/42926796-184b6bfc-8b50-11e8-93fb-02d833eeac16.png)
![screenshot from 2018-07-19 02-39-44](https://user-images.githubusercontent.com/6755456/42926805-1c6af95a-8b50-11e8-9cfe-4de64630ddc5.png)
![screenshot from 2018-07-19 02-40-26](https://user-images.githubusercontent.com/6755456/42926809-1f9119e8-8b50-11e8-9543-ee6a95bac988.png)
![screenshot from 2018-07-19 02-43-28](https://user-images.githubusercontent.com/6755456/42926815-2327dcc2-8b50-11e8-8931-a5782c3c8504.png)
![screenshot from 2018-07-19 02-50-48](https://user-images.githubusercontent.com/6755456/42926820-27ae816a-8b50-11e8-9983-b8bc45e322be.png)
![screenshot from 2018-07-19 02-52-11](https://user-images.githubusercontent.com/6755456/42926828-2c80cad6-8b50-11e8-9346-100c0d737837.png)
![screenshot from 2018-07-19 02-52-18](https://user-images.githubusercontent.com/6755456/42926839-3348b57c-8b50-11e8-9ae9-f13f2ace9993.png)
![screenshot from 2018-07-19 02-52-40](https://user-images.githubusercontent.com/6755456/42926849-373106d0-8b50-11e8-9517-20f0d76708d7.png)
![screenshot from 2018-07-19 02-52-58](https://user-images.githubusercontent.com/6755456/42926854-3c3e7c20-8b50-11e8-9051-c7c307fafbfc.png)

**Comment by SandeepKumarJoshi** [comment]
@reddalexx: Any update on the above issue?

**Comment by talalzahid91** [comment]
@SandeepKumarJoshi @reddalexx 
 I am having the same issues. For the first approach "lexpredict-contraxsuite-deploy", i used the script to copy the settings but then I ran to celery issue that is the application could not find "apps" worker.
The second approach docker also does not work. The dockers are deployed but it shows the same errors for me as @SandeepKumarJoshi . Any help would suffice. Thanks.

**Comment by SunnyMalikMicroland** [comment]
I ran into the same issue:
The SECRET_KEY setting must not be empty 
Udpate base/fabricrc with the SECRET Key
SECRET_KEY = <secret key without @ to be specified without key>

Application is now up with few other issues like Email verification and Super User Account but was able to fix that.
